[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python -m uvicorn api_gateway:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

# Environment variables configuration
[environment]
NODE_ENV = "production"
PYTHONUNBUFFERED = "1"

# Service configuration
[[services]]
name = "api"
# Internal port that Railway will map
internalPort = 8000
# Protocol
protocol = "tcp"

# Scaling configuration
[scaling]
minReplicas = 1
maxReplicas = 3

# Resource limits
[resources]
memory = "2Gi"
cpu = "1000m"

# Build configuration
[build.env]
PYTHON_VERSION = "3.11"

# Railway-specific settings
[railway]
# Enable private networking for internal service communication
privateNetworkEnabled = true

# Volumes for persistent storage (ChromaDB)
[[volumes]]
name = "chroma-storage"
mountPath = "/app/chroma_db"

# Cron jobs (optional - for maintenance tasks)
[[crons]]
name = "cleanup-old-sessions"
schedule = "0 2 * * *"  # Daily at 2 AM
command = "python -m agent.cleanup_sessions"